apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded

spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "api-user.name" . }}
        app_name: api-user
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Never
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          restartPoliciy: Never
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.configs.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: ["/bin/sh", "-c"]
          args:
            - NODE_ENV=dev npm ci &&
              npx ts-node --transpile-only ./node_modules/typeorm/cli.js migration:run

